name: Demo exploit 2

on:
  issues:
    types: [opened]
    
jobs:
  parse-issue-do-something:
    runs-on: self-hosted
    steps:
    - name: Get JSON Data out of Issue
      uses: peter-murray/issue-body-parser-action@v2
      id: issue_body_parser_request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_id: ${{ github.event.issue.number }}
    - name: Do something
      id: do-something
      uses: actions/github-script@main
      with:
        script: |
          const options = { token: '${{ secrets.TOKEN }}', adminOpsOrg: '${{ secrets.ADMIN_OPS_ORG }}', actionsApprovedOrg: '${{ secrets.ACTIONS_APPROVED_ORG }}', actionsApproverTeam: '${{ secrets.ACTIONS_APPROVERS_TEAM }}', baseUrl: '${{ github.api_url }}', version: '${{ fromJson(steps.issue_body_parser_request.outputs.payload).version }}' };
