name: Demo exploit 1

on:
  issues:
    types: [opened]
    
jobs:
  parse-issue-do-something:
    runs-on: ubuntu-latest
    steps:
    - name: Get JSON Data out of Issue
      uses: peter-murray/issue-body-parser-action@v2
      id: issue_body_parser_request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_id: ${{ github.event.issue.number }}
    - name: Do something
      id: do-something
      run: |
        echo "VERSION: ${{ fromJson(steps.issue_body_parser_request.outputs.payload).version }}"
